version: "3.7"
services:
  cadvisor:
    container_name: cadvisor
    ports:
      - 8080:8080
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: -housekeeping_interval=30s
    restart: always
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.1.2
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    command: --collector.disable-defaults --collector.cpufreq --collector.cpu --collector.diskstats --collector.filesystem --collector.meminfo 
    restart: always

networks:
  default:
    name: monitoring

